Membrane AAC filler element
membraneframework/membrane_aac_plugin pull request #1
Opened 2020-05-25 18:37 UTC by Hajto

2020-05-26 07:33 UTC, mat-hek requested changes

2020-05-26 07:33 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +  end
it's overkill imho, especially since the state is always accessed via the map API and thus there are no benefits from it being struct anyway

2020-05-26 07:33 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +  def silent_frame, do: @silent_frame
add docs, preferably move before the impl functions

2020-05-26 07:33 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +  def_options init_timestamp: [default: nil]
add type and doc

2020-05-26 07:33 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +  Element that feels gaps in AAC stream with silent frames.
*fills

2020-05-26 07:33 UTC, mat-hek commented on .circleci/config.yml
> +      - image: membrane/bionic-membrane:latest
use membrane/membrane:latest

2020-05-26 07:33 UTC, mat-hek commented on test/membrane/aac/filler_test.exs
> +defmodule Membrane.AAC.FillerTest do
an integration test would be useful

2020-05-26 07:33 UTC, mat-hek commented on README.md
> +[![CircleCI](https://circleci.com/gh/membraneframework/membrane_aac.svg?style=svg)](https://circleci.com/gh/membraneframework/membrane_aac)
```suggestion
[![CircleCI](https://circleci.com/gh/membraneframework/membrane_aac_plugin.svg?style=svg)](https://circleci.com/gh/membraneframework/membrane_aac_plugin)
```

applies to all the occurences

2020-05-27 12:14 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +  Element that feels gaps in AAC stream with silent frames.
🤦

2020-05-27 13:18 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +  def_options init_timestamp: [default: nil]
as we have discused on slack, this is to be removed immediately, due to the fact that default is zero.

2020-05-27 13:19 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +  def silent_frame, do: @silent_frame
moved, addes spec and doc

2020-05-27 19:58 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +  end
On one occasion either Jose or Radek Szymczyszyn (prelection about best practices in erlang) recommended this approach for maps that have fixed keys. It prevents potential stupid bugs, it's easier to read (you know which keys references to expect when working with this entity) etc. Thus I prefer to use it whenever there is GenServer or process state.

2020-05-27 19:58 UTC, Hajto commented on test/membrane/aac/filler_test.exs
> +defmodule Membrane.AAC.FillerTest do
added

2020-05-27 20:01 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +  @caps {Membrane.Caps.Audio.AAC, profile: :LC, channels: 1}
I removed specifications of frame rate and size here as I have noticed this element has provisions of supporting any  of those as long as the sample_rate > samples_per_frame, am I correct?

2020-05-27 20:01 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +  @caps {Membrane.Caps.Audio.AAC, profile: :LC, channels: 1}
@mat-hek

2020-06-01 10:48 UTC, mat-hek requested changes

2020-06-01 10:48 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +    IO.inspect(current_timestamp, label: "current")
remove

2020-06-01 10:48 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +    @doc """
module-level constants are private to the module and cannot be documented, so the doc will refer to the next undocumented function below if defined. Make it a comment

2020-06-01 10:48 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +  @caps {Membrane.Caps.Audio.AAC, profile: :LC, channels: 1}
Frame length used to be hardcoded, but since now it's taken from caps, this should be correct ;) However, channels could be also taken from caps, and a double-channel frame can be injected when needed

2020-06-01 10:48 UTC, mat-hek commented on test/membrane/aac/filler_test.exs
> +        assert_sink_buffer(pipeline, :sink, %Buffer{payload: ^target_payload})
This way you don't ensure the order of the buffers. Rather do 
```suggestion
        assert_sink_buffer(pipeline, :sink, %Buffer{payload: payload})
        assert payload == target_payload
```

2020-06-01 10:48 UTC, mat-hek commented on test/membrane/aac/filler_test.exs
> +      end
Check whether no other buffer comes in. Since end of stream has already been received, use 0 timeout so that test can finish faster

2020-06-01 10:48 UTC, mat-hek commented on test/membrane/aac/filler_test.exs
> +      assert_end_of_stream(pipeline, :sink)
move this assertion to the end, here it can lead to timeout in case of longer buffer processing. instead, assert_start_of_stream would be helpful in this place

2020-06-01 11:55 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +  end
On the other hand, it doesn't help in any way when you use the dot notation or omit the struct name when matching or updating. Also, I think most benefits of using structs show up when dealing with APIs, not internal states. Nevertheless, I don't insist on switching to a bare map whenever you see significant profits of using struct.

2020-06-03 14:34 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +  @caps {Membrane.Caps.Audio.AAC, profile: :LC, channels: 1}
I don't know how channels work. Will silent frame be the same for two channels or does it have to be modified?

2020-06-03 19:45 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +  @caps {Membrane.Caps.Audio.AAC, profile: :LC, channels: 1}
I think it'll differ, you can generate one with ffmpeg

2020-06-10 10:39 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +    IO.inspect(current_timestamp, label: "current")
Removed

2020-06-10 10:40 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +    @doc """
Fixed

2020-06-10 10:59 UTC, Hajto commented on test/membrane/aac/filler_test.exs
> +        assert_sink_buffer(pipeline, :sink, %Buffer{payload: ^target_payload})
Done

2020-06-10 13:58 UTC, mat-hek requested changes

2020-06-10 13:58 UTC, mat-hek commented on test/membrane/aac/filler_test.exs
> +      assert_end_of_stream(pipeline, :sink)
```suggestion
      assert_end_of_stream(pipeline, :sink)
      refute_sink_buffer(pipeline, :sink, _, 0)
```

2020-06-22 10:14 UTC, Hajto commented on lib/membrane/aac/filler.ex
> +  @caps {Membrane.Caps.Audio.AAC, profile: :LC, channels: 1}
Can we make an issue out of this to be resolved later?

2020-06-22 10:23 UTC, mat-hek commented on lib/membrane/aac/filler.ex
> +  @caps {Membrane.Caps.Audio.AAC, profile: :LC, channels: 1}
Yes, but let's put it in the todo list

2020-06-22 10:24 UTC, mat-hek approved these changes

2020-06-22 10:57 UTC, merged