Parser
membraneframework/membrane_aac_plugin pull request #2
Opened 2020-06-01 11:58 UTC by mat-hek

Should be merged after #1

2020-06-02 11:56 UTC, Hajto requested changes

2020-06-02 11:56 UTC, Hajto commented on lib/membrane/aac/parser.ex
> +    state = options |> Map.from_struct() |> Map.merge(%{leftover: <<>>, timestamp: 0})
I know you are not a fan of using structs, but maybe you should consider adding a typespec that describes the state. It would be immediate information for person that may touch this in the future.

2020-06-02 11:56 UTC, Hajto commented on mix.exs
> +      {:membrane_aac_format, github: "membraneframework/membrane_aac_format", branch: "develop"},
Maybe that package should be released first. It has only one PR and it is approved.

2020-06-02 11:56 UTC, Hajto commented on lib/membrane/aac/parser/helper.ex
> +           {[{:caps, AAC.t()} | {:buffer, Buffer.t()}], binary, timestamp :: Ratio.t() | Time.t()}}
Why is Ratio.t or Time.t?

2020-06-02 11:56 UTC, Hajto commented on lib/membrane/aac/parser/helper.ex
> +  defp parse_header(
I think it may be a not bad idea to move purely AAC related stuff to its own module and test it independently.

2020-06-02 11:56 UTC, Hajto commented on lib/membrane/aac/parser/helper.ex
> +    frame_size = size - adts_size
If the encapsulation is not ADTS you skip the atds, would you mind explaining why this happens? Isn't adts characteristic to atds stream?

2020-06-02 11:56 UTC, Hajto commented on lib/membrane/aac/parser/helper.ex
> +    frame_size = size - adts_size
I've seen that header saids only ATDS is supported now, but no ATDS encapsulation suggests otherwise. I am just a bit confused.

2020-06-02 11:56 UTC, Hajto commented on lib/membrane/aac/parser/helper.ex
> +  @spec parse_adts(binary, AAC.t(), timestamp :: Ratio.t() | Time.t(), %{
Why not make the timestamp homogenous and make sure it's always a ratio?

2020-06-02 11:56 UTC, Hajto commented on lib/membrane/aac/parser/helper.ex
> +  @spec parse_adts(binary, AAC.t(), timestamp :: Ratio.t() | Time.t(), %{
Or make a type for timestamp.

2020-06-02 11:56 UTC, Hajto commented on lib/membrane/aac/parser/helper.ex
> +  @spec parse_adts(binary, AAC.t(), timestamp :: Ratio.t() | Time.t(), %{
A tiny bit of documentation would be nice. I get that this is a private module by a comment or two of internal docs would be beneficial for longer-term maintainability.

2020-06-02 11:56 UTC, Hajto commented on lib/membrane/aac/parser/helper.ex
> +          encapsulation: :none | :ADTS
Shouldn't this support anything that is supplied here:
https://github.com/membraneframework/membrane_aac_plugin/pull/2/files#diff-080d94d064d825e4b49dc42677d41350R18
??

2020-06-02 12:14 UTC, mat-hek commented on lib/membrane/aac/parser/helper.ex
> +           {[{:caps, AAC.t()} | {:buffer, Buffer.t()}], binary, timestamp :: Ratio.t() | Time.t()}}
Because Ratio automagically simplifies to integer when possible, and then it's actually `Time.t`. It should be `Ratio.t(Time.t) | Time.t`, but `Ratio.t` cannot be parametrized. This needs to be specified at the core level though.

2020-06-02 12:20 UTC, mat-hek commented on lib/membrane/aac/parser/helper.ex
> +  defp parse_header(
Well, this actually is in a specific module for purely AAC related stuff...

2020-06-02 12:26 UTC, mat-hek commented on lib/membrane/aac/parser.ex
> +    state = options |> Map.from_struct() |> Map.merge(%{leftover: <<>>, timestamp: 0})
I believe it's specified very clearly in this line. Anyway, when I try to define a private type for this, the compiler warns that the type is unused, and actually there's no place to use it.

2020-06-03 10:24 UTC, Hajto approved these changes

2020-06-22 13:58 UTC, merged