Handle AOT specific channels. Bump to v0.18.2
membraneframework/membrane_aac_plugin pull request #44
Opened 2024-06-12 14:43 UTC by varsill

2026-06-08 09:11 UTC, Noarkhh requested changes
handling `:AOT_specific` is fine, replacing `AAC.t()` with `map()` should be reverted

2026-06-08 16:28 UTC, varsill commented on lib/membrane/aac/parser/audio_specific_config.ex
> +          :AOT_specific -> nil
we need to convert it here since AAC doesn't allow for `:AOT_specific` `channels` (perhaps it should though 🤷 )

2026-06-09 10:42 UTC, Noarkhh approved these changes

2026-06-09 10:42 UTC, Noarkhh commented on lib/membrane/aac/parser/audio_specific_config.ex
> +          :AOT_specific -> nil
I think it would only be valid if somehow the channel_id was known, but not aot_id, and I don't think it's a situation that happens

2026-06-09 10:44 UTC, merged